### ISSUE TITLE
can't find the 'obtain_attach_nodes_by_influential' method

### ISSUE THREAD

**Issue by FantasticCode2019** [ventr1c/UGBA#3]
hi! when reading this code, I find this error. I hope you can note that. Thank you for your help in advance.

**Comment by ventr1c** [comment]
Hi, thanks for your notice! Since the 'obtain_attach_nodes_by_influential' function has been deprecated in our current version of codes. You can directly remove it from the code. We will also clean this duplicate codes in the future version soon. Thanks again!

**Comment by FantasticCode2019** [comment]
ok, thanks!
